---
- name: SSH do Rundeck
  hosts: devops
  tasks:
   - name: Copy Remote-To-Remote (from serverA to serverB)
     synchronize: src=/var/lib/rundeck/.ssh/id_rsa.pub dest=/tmp/
     delegate_to: automation.salas4linux.com.br

- name: Authorized_keys
  hosts: all
  tasks:
    - name: Setar authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
