---
- name: Remove versoes antigas do docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io 
- name: Instala Dependencias
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
